name: Do some testing 
on: [push]

jobs:
  build:
    name: Python Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib scipy 
      - name: Test with pytest
        run: |
          pip install pytest hypothesis pytest-benchmark
          pytest -rA
