name: Do some testing 
on: [push]

jobs:
  build:
    name: Python Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest ; pwd ; ls -la .. ; ls -la /github/home ; ls -la /github/workflow ; ls -la /

